### PR TITLE
Add option to add distractors

### PR DESCRIPTION
**Pull request by otacke**
If this is merged in, the content type can cover the new user story: "As a teacher, I can define extra texts as draggables that are always wrong (distractors)".

Was requested at https://h5p.org/node/90464 for instance

### CODE REVIEW

**Comment by kevlb** [comment]
I see your comment from 1 Sep:
@otacke otacke force-pushed the otacke:add-distractors  branch from c0959c9 to ed952c4 on 1 Sep
Does this mean it's now available in H5P?

**Comment by otacke** [comment]
@kevlb What does the message say I pushed to?
So: No. You cannot force a push to other people's repositories, of course. :-)

**Comment by niikoo** [comment]
Any ETA on this one?

**Comment by otacke** [comment]
@niikoo I don't think the H5P core teams gives out estimates on pull request approvals or dismissals.

**Comment by warwick-bailey-work** [comment]
Has the add-distractors feature been added to the drag the words question type?

**Comment by mariogalmonte** [comment]
Hi. I think this is a must-have for Drag the Words content type. I've just seen the last commits and I was wondering if this coould be added soon to the master.

**Comment by otacke** [comment]
@mariogalmonte As a matter of fact, I know that the H5P core team is about to take care of this pull request shortly.

**Comment by Craig88** [comment]
Can someone please explain how to use this feature using the H5P editor?
How do I add a distractor?

**Comment by otacke** [comment]
@Craig88 You wait a little, then H5P Group is going to release the update, then you update the content type, and then you'll find the option in the settings 😉

**Comment by Craig88** [comment]
@otacke - Perfect. Thank you. I will be patient 😀

**Pull request merged**
